package com.graphite.competitionplanner.common.exception

enum class BadRequestType {
    CATEGORY_CANNOT_DELETE_WITH_PLAYERS,
    CATEGORY_NOT_VALID,
    CATEGORY_ALREADY_ADDED,
    CATEGORY_CANNOT_UPDATE_AFTER_DRAW,
    CLUB_NAME_NOT_UNIQUE,
    DRAW_NOT_ENOUGH_REGISTRATIONS,
    DRAW_TOO_MANY_SEEDED,
    DRAW_TOO_FEW_SEEDED,
    PLAYER_ALREADY_REGISTERED,
    REGISTRATION_WRONG_CATEGORY_TYPE,
    GAME_TOO_FEW_SETS_REPORTED,
    GAME_TOO_FEW_POINTS_IN_SET,
    GAME_TOO_MANY_POINTS_IN_SET,
    GAME_COULD_NOT_DECIDE_WINNER,
    GAME_TOO_MANY_SETS_REPORTED,
    GAME_NOT_ENOUGH_WIN_MARGIN,
    SCHEDULE_TOO_FEW_TIMESLOTS,
    RESULT_CANNOT_DELETE
}